### ISSUE TITLE
Dosn't work? 

### ISSUE THREAD

**Issue by chavenor** [onlyhavecans/dnsimple-python#25]
I can't seem to get it to Authorize? 

Is this up-to-date with the current API -- I don't see python listed on the site? 

Thanks! 

Casey

**Comment by reagent** [comment]
I'm pretty sure this covers only version 1 of the API -- are you trying to use v2?  If not, post some sample code and I can try to help.

**Comment by chavenor** [comment]
Already started writing my own API connector.  Will be done within the next couple of days.

**Comment by reagent** [comment]
There's also this that supports v1 that @onlyhavecans and I have collaborated on:

https://github.com/vigetlabs/dnsimple
