### ISSUE TITLE
1.0.1 pip install failing

### ISSUE THREAD

**Issue by glasnt** [onlyhavecans/dnsimple-python#32]
I'm unable to `pip install` 1.0.1, it's failing on `NameError: name 'AuthBase' is not defined`

The same error is happening in travis, but the build doesn't fail because of this. 

https://travis-ci.org/onlyhavecans/dnsimple-python/jobs/344629037#L474

```
Traceback (most recent call last):
  File "setup.py", line 6, in <module>
    from dnsimple import dnsimple
  File "/home/travis/build/onlyhavecans/dnsimple-python/dnsimple/__init__.py", line 5, in <module>
    from dnsimple.dnsimple import DNSimple, DNSimpleException, DNSimpleAuthException
  File "/home/travis/build/onlyhavecans/dnsimple-python/dnsimple/dnsimple.py", line 47, in <module>
    class DNSimpleTokenAuth(AuthBase):
NameError: name 'AuthBase' is not defined
```

As an aside: was the removal of the the 0.3.6 package from pypi intentional?

**Comment by bartmeuris** [comment]
Same issue here.

**Comment by onlyhavecans** [comment]
Sorry I was not notified about this. I was not pinged on this ticket. I will fix this today.

I show 0.3.6 is still up https://pypi.python.org/pypi/dnsimple/0.3.6

**Comment by onlyhavecans** [comment]
I deployed 1.0.2 as a hotfix to resolve the issue with PIP. Can you please verify you have no more problems? @bartmeuris  @glasnt

**Comment by glasnt** [comment]
@onlyhavecans both 0.3.6 and 1.0.2 now install cleanly now. Thanks!
