### ISSUE TITLE
Add to PyPi

### ISSUE THREAD

**Issue by drpotato** [onlyhavecans/dnsimple-python#9]
Could you please add dnsimple-python package to PyPi? It would be much easier to deploy project using your awesome package.

Cheers :)

**Comment by nebstrebor** [comment]
It seemed to be working to install it directly from github, but I am now seeing some issues installing it from github via pip...any luck updating pypi? 

When i try to install it from a requirements file that references the github address, i get 
```
Running setup.py (path:/Users/ben/Envs/test2345/build/dnsimple-python/setup.py) egg_info for package dnsimple-python
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/Users/ben/Envs/test2345/build/dnsimple-python/setup.py", line 6, in <module>
        from dnsimple import dnsimple
      File "dnsimple/__init__.py", line 5, in <module>
        from dnsimple.dnsimple import DNSimple, DNSimpleException
      File "dnsimple/dnsimple.py", line 25, in <module>
        from requests import Request, Session, ConnectionError, HTTPError
    ImportError: No module named requests
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/Users/ben/Envs/test2345/build/dnsimple-python/setup.py", line 6, in <module>

    from dnsimple import dnsimple

  File "dnsimple/__init__.py", line 5, in <module>

    from dnsimple.dnsimple import DNSimple, DNSimpleException

  File "dnsimple/dnsimple.py", line 25, in <module>

    from requests import Request, Session, ConnectionError, HTTPError

ImportError: No module named requests
```
even though requests is listed in the requirements file higher up.

**Comment by davidquarles** [comment]
we just installed directly from github as well, which seems to be working, but is there any update with merging #16 / updating PyPi here?

**Comment by mikemaccana** [comment]
Merged. But I really want someone else to take it over (and move it to
python requests) - I hack node all day these days!

**Comment by andrenarchy** [comment]
Hmm, I still get `0.1.0` from PyPi... Any updates?

**Comment by andrenarchy** [comment]
@mikemaccana Could you upload the current version to PyPi?

**Comment by fesplugas** [comment]
:+1: to upload current version to PyPi.

**Comment by tbunnyman** [comment]
Someone else currently controls the PyPi repo. There is a ticket here to have permissions moved over. We are trying to contact the original owner to get this moved
https://sourceforge.net/p/pypi/support-requests/645/

**Comment by onlyhavecans** [comment]
Pushed 0.3.6 to PyPi
